# Define the services (containers) for your application
services:
  topic_finder:
    # Build the Docker image using the Dockerfile in the current directory
    build: .
    # Map port 5000 on the host to port 5000 in the container
    ports:
      - "4001:5000"
    # Define environment variables within the container
    environment:
      # Set the Flask environment mode.
      FLASK_ENV: development
      # Set NLTK_DATA environment variable to point to the volume
      NLTK_DATA: /nltk_data
    # Define the command to run when the container starts
    command: >
      sh -c "if [ \"$$FLASK_ENV\" = \"production\" ]; then
        # If in production mode, run the app using Gunicorn
        gunicorn --bind 0.0.0.0:5000 app:app;
      else
        # If in development mode, run the app using Flask's built-in development server
        flask run --host=0.0.0.0;
      fi"
    # Mount volumes for persistent storage
    volumes:
      # Mount a local directory for NLTK data
      - ./nltk_data:/nltk_data
      # Optional: Mount the current directory into the container for easier development
      # - .:/app