# https://taskfile.dev

version: '3'

tasks:

  up_dev:
    aliases:
      - up
      - start
    cmds:
      - docker compose up -d

  up_build:
    cmds:
      - docker compose up -d --build

  down:
    aliases:
      - stop
    cmds:
      - docker compose down

  up_prod:
    cmds:
      - docker compose -f docker-compose-prod.yml up -d

  up_build_prod:
    cmds:
      - docker compose -f docker-compose-prod.yml up -d --build



